### PR TITLE
 Defaultly install man pages.

### PR DESCRIPTION
**Pull request by KazuakiM**
It will merge after a few weeks.
We will wait for your feedback.

### CODE REVIEW

**Comment by masatake** [comment]
My understanding is that this pull request provides `docutils` in which rst2man is available.
However, as far as reading the log output on Travis, I cannot find any mark that `docutils` is introduced well to the build-environment. Am I missing something?

Is there anyway to make the log level higher to known whether `docutils` is introduced well or not?

**Comment by cweagans** [comment]
The Travis configuration isn't actually testing the contents of each PR. It's testing whatever is in master. I'll resolve this in another PR.

**Comment by cweagans** [comment]
Merge https://github.com/universal-ctags/homebrew-universal-ctags/pull/27 first, then rebase this one and revisit.

**Comment by masatake** [comment]
It works find now, doesn't it?

**Comment by cweagans** [comment]
Yes, looks good to me.

**Comment by KazuakiM** [comment]
@masatake , @cweagans 
Yes , it works.

**Pull request merged**
