### PR TITLE
 Support TravisCI

### PR DESCRIPTION
**Pull request by KazuakiM**

### CODE REVIEW

**Comment by cweagans** [comment]
:+1:

**Comment by KazuakiM** [comment]
😃

**Comment by KazuakiM** [comment]
@masatake @cweagans 
Could you have admin rights at TravisCI ? I don't have  admin rights.
https://travis-ci.org/profile/universal-ctags

**Comment by masatake** [comment]
I made an invitation. Could you check that you get the right?

**Comment by KazuakiM** [comment]
Thank you.
I got admin rights.

**Pull request merged**
