### PR TITLE
Add lines for debugging #23 part 1

### PR DESCRIPTION
**Pull request by masatake**
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by masatake** [comment]
@KazuakiM, is there any way to ignore command failures?

I would like to run "./install-sh" even though I know it fails. I would like to see the error message for the failed execution.

**Comment by masatake** [comment]
It seems that the make command installed to the travis-ci doesn't have --trace option.
I wonder how I can provide the way to fall back.

**Comment by KazuakiM** [comment]
@masatake 
My mac's make(GNU Make 3.81 for i386-apple-darwin11.3.0) command isn't `--trace` options too.
So use `make -d` or `make --debug[=flags]`.
```
OPTIONS
       -d   Print debugging information in addition to normal processing.  The debugging information says which files are being considered for remaking,
            which file-times are being compared and with what results, which files actually need to be remade, which implicit rules are  considered  and
            which are applied---everything interesting about how make decides what to do.

       --debug[=FLAGS]
            Print  debugging  information in addition to normal processing.  If the FLAGS are omitted, then the behavior is the same as if -d was speci-
            fied.  FLAGS may be a for all debugging output (same as using -d), b for basic debugging, v for more verbose basic debugging, i for  showing
            implicit rules, j for details on invocation of commands, and m for debugging while remaking makefiles.
```

**Comment by masatake** [comment]
@KazuakiM, thank you. It seems that --trace option that I would like to use was introduced in 3.82.

**Comment by masatake** [comment]
@KazuakiM, how can I see the full output of brew that runs on travis?
```
==> ls -l
==> ./install-sh --help
```

I can see the executed command lines. However, I cannot see the output.
I would like to see the output on travis. Not your environment.
We have to inject more debug code to our build scripts for solve the issue.

**Comment by masatake** [comment]
@KazuakiM, can we make a branch for debugging in this repository?
We have to understand deeply what happens on "install-sh" at @paradox460's mac.
We have to inject much debug-print lines that makes the repository dirty.
To keep the master branch clean, we should make a branch for debugging. And we ask @paradox460 try the branch. The branch name will be `for-debugging-issue-23-strange-install-sh` or something.

I put what I can image as the debug-print lines now to this pull reqeust.
Could you merge this to the `for-debugging-issue-23-strange-install-sh` branch?
@paradox460, could you try the branch instead of "master" branch?
I would like to show the output.

**Comment by KazuakiM** [comment]
@masatake 
I'm out this week on summer vacation.
I'll do it this weekend.

**Comment by masatake** [comment]
@KazuakiM, oh, I see. Have a nice vacation!

**Comment by KazuakiM** [comment]
@masatake 
I made `for-debugging-issue-23-strange-install-sh` branch on this repository.
I want to ask you once again PR for `for-debugging-issue-23-strange-install-sh` branch.

**Comment by KazuakiM** [comment]
@masatake 
I look this gif. And Install fomula `00:48 - install
/usr/local/Homebrew/Library/Taps/universal-ctags/homebrew-universal-ctags/universal-ctags.rb` is as I expected.
but install is not working well.
Would you like to merge this PR.

https://github.com/universal-ctags/homebrew-universal-ctags/issues/23#issuecomment-420176937

**Comment by masatake** [comment]
@KazuakiM, do you mean you will merge this PR to the master branch?
If yes, I am afraid that the master branch becomes dirty with commits for debugging.
Is it o.k.?

**Pull request closed without merging**
